### ISSUE TITLE
share

### ISSUE THREAD

**Issue by trungtran999** [nguyenminh1998/Project-KTLT2#1]
[Book_Data.txt](https://github.com/nguyenminh1998/Project-KTLT2/files/3250286/Book_Data.txt)
[dangnhap.txt](https://github.com/nguyenminh1998/Project-KTLT2/files/3250287/dangnhap.txt)
[phieumuon.txt](https://github.com/nguyenminh1998/Project-KTLT2/files/3250288/phieumuon.txt)
[sach.txt](https://github.com/nguyenminh1998/Project-KTLT2/files/3250289/sach.txt)
[User_Data.txt](https://github.com/nguyenminh1998/Project-KTLT2/files/3250290/User_Data.txt)

**Comment by nguyenminh1998** [comment]
[GiaoVien (2).txt](https://github.com/nguyenminh1998/Project-KTLT2/files/3250315/GiaoVien.2.txt)
[GiaoVien.txt](https://github.com/nguyenminh1998/Project-KTLT2/files/3250316/GiaoVien.txt)
